### ISSUE TITLE
Example yaml with kubernetes 

### ISSUE THREAD

**Issue by digeler** [bryanklewis/prometheus-eventhubs-adapter#17]
Great Job.
Can you share a fully yaml template with the passing of the flags,For kubernetes
And also example of name mapping for using adx with prometheus.
Thank you.

**Comment by bryanklewis** [comment]
a kubernetes yaml template is a good idea, appreciate the input. Im not a regular kubernetes developer in my day to day so this would take a bit of googling for me. In theory it would be very similar to any other basic service template out there.

For the name mapping question im a little unsure what your asking. If your referring to the flag, thats simply the name of the ingestion mapping object created for the target ADX table. Its an end user defined name, so it could be whatever. If your looking for an example kusto map definition on a table, the kusto docs have [examples for creating those](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/create-ingestion-mapping-command). If you look at the json model on the README.md for this project it shows how events are written, i would map the datatypes as follows:
{
  "timestamp": "1970-01-01T00:00:00Z", --->datetime
  "value": "373.71", ---> real
  "name": "process_cpu_seconds_total", ---> string
  "labels": { ---> dynamic
    "label1": "value1",
    "label2": "value2"
  }
}

**Comment by digeler** [comment]
thanks i managed ,there is a wizard to create mapping in azure portal.
