### ISSUE TITLE
ADAP_LISTEN_ADDRESS is ignored

### ISSUE THREAD

**Issue by mbiagetti** [bryanklewis/prometheus-eventhubs-adapter#20]
The listen address env argument is ignored because hardcoded in the dockerfile ENTRYPOINT

**Comment by bryanklewis** [comment]
oh good call. thank-you for taking the time to point that out.

**Comment by mbiagetti** [comment]
Thanks to you @bryanklewis

**Comment by mbiagetti** [comment]
@bryanklewis Let me know if you can tag a new release 🙏

**Comment by bryanklewis** [comment]
@mbiagetti yes, will do

**Comment by mbiagetti** [comment]
Hi @bryanklewis thanks again for your time 🙌
