### ISSUE TITLE
Please update readme with details about "adapter-address"

### ISSUE THREAD

**Issue by vinprogramming** [bryanklewis/prometheus-eventhubs-adapter#22]
remote_write:
  - url: "http://<adapter-address>:9201/write"
It is mentioned to add this in prometheus configuration file. But can you please update info about what adapter-address is and how to find it?

Thanks.

**Comment by bryanklewis** [comment]
Its the host name of wherever you are running THIS prometheus-eventhubs-adapter application. You can learn more about the Prometheus configuration here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

**Comment by vinprogramming** [comment]
Thanks a lot!
